version: '3'

services:
  kafka-consumer:
    build:
      context: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=your kafka bootstrap server link
    deploy:
      replicas: 3  # Adjust the number of replicas as needed
