version: '3'

services:
  kafka-consumer:
    build:
      context: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
    deploy:
      replicas: 3  # Adjust the number of replicas as needed
